#!/bin/bash
#Helper script
#non-v1 didn't have a built-in updater

BASEDIR=sm64-port-android
VERSION=1
VCHECK=https://raw.githubusercontent.com/VDavid003/sm64AndroidBuilder/master/helperVersion
UPDATE=https://raw.githubusercontent.com/VDavid003/sm64AndroidBuilder/master/sm64AndroidBuilder2
ONLINEVERSION=$(wget -q -O - $VCHECK)
if [ -z $ONLINEVERSION ]; then ONLINEVERSION=0; fi

fail() {
	echo "$1"
	exit 1
}

if [ $ONLINEVERSION -gt $VERSION ];
then
	wget $UPDATE -O sm64AndroidBuilder2
	./sm64AndroidBuilder2 "$@"
	exit 0
fi

case "$1" in
# init
"init")
	rm -rf $BASEDIR
	git clone https://github.com/VDavid003/sm64-port-android $BASEDIR || fail "Failed to clone! Check your network connection!"
	pushd $BASEDIR
	./getSDL.sh
	popd
	;;
"make")
	shift
	while [[ $# -gt 0 ]]
	do
		key="$1"
		shift
		case $key in
			#make params, -p <params>
			-p|--parameters)
				PARAMS=$1
				shift
				;;
			#reset tree
			-r|--reset)
				RESET=1
				;;
			#make clean
			-c|--clean)
				CLEAN=1
				;;
			#update source code
			-u|--update)
				UPDATE=1
				;;
			#branch, -b <branch>
			-b|--branch)
				BRANCH=$1
				shift
				;;
		esac
	done

	pushd  $BASEDIR

	if [ ! -z "$RESET" ];
	then
		mv *.z64 .git #Yes I know I'm moving it to .git but it's temporary so it's okay
		rm -rf ./*
		git reset --hard
		mv .git/*.z64 .
	fi

	if [ ! -z "$BRANCH" ] && [ ! $(git symbolic-ref --short -q HEAD) = $BRANCH ];
	then
		git checkout $BRANCH || fail "Failed to switch branch! Try resetting!"
	fi

	if [ ! -z "$UPDATE" ];
	then
		git reset --hard
		git pull || fail "Failed to update! Check your network connection!"
	fi

	if [ ! -z "$CLEAN" ]; then make clean; fi
	make $PARAMS
	popd
esac
